#!/usr/bin/env python3
"""KickBake builder — embed a Kickstart into a Fedora Plasma ISO.

Principle: Kickstart/ISO = machine birth. Ansible = machine personality.
Nothing post-install lives here.

All Fedora tooling (mkksiso, ksvalidator) runs inside an ephemeral Podman
container built from podman/Containerfile. The host needs only:

    python3 >= 3.11 (stdlib only) and podman

Commands:
    doctor      check host deps, build toolchain image, report tool versions
    verify-iso  sha256 the source ISO against the pinned official hash
    pin-iso     verify a NEW ISO and pin it (source + hash in config;
                user-driven: no download, no discovery)
    flatten     resolve the kickstart %include tree into one self-contained file
    validate    run ksvalidator (pykickstart) inside the container
    build       verify + flatten + validate + mkksiso, then emit output/*.sha256

Usage:
    python3 kickbake.py doctor
    python3 kickbake.py build
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

try:
    import tomllib  # python >= 3.11
except ModuleNotFoundError:  # pragma: no cover - reported by doctor
    tomllib = None

__version__ = "1.0.1"

ROOT = Path(__file__).resolve().parent
DEFAULT_CONFIG = ROOT / "config" / "kickbake.toml"

INCLUDE_RE = re.compile(r"^\s*%include\s+(.+?)\s*$")

# pykickstart's BTRFSData.__eq__ compares ONLY mountpoints, so declaring two
# btrfs volumes (each necessarily "btrfs none --label=... <dev>") trips a
# "duplicate" warning. Verified against pykickstart 3.69 (F44): such files
# parse fully and every volume/subvolume entry survives intact. Anaconda
# consumes the same parse result. If Fedora ever makes this a real error,
# the strict failure path below re-engages automatically.
KNOWN_COSMETIC_WARNINGS = (
    "A btrfs volume with the mountpoint none has already been defined.",
)


class BuildError(RuntimeError):
    """Fatal, user-facing error."""


# --------------------------------------------------------------------------
# configuration
# --------------------------------------------------------------------------

def load_config(path: Path) -> dict:
    if tomllib is None:
        raise BuildError(
            "python3 >= 3.11 is required (stdlib tomllib not available); "
            f"running: {sys.version.split()[0]}"
        )
    try:
        with path.open("rb") as fh:
            cfg = tomllib.load(fh)
    except FileNotFoundError:
        raise BuildError(f"config not found: {path}")
    except tomllib.TOMLDecodeError as exc:
        raise BuildError(f"invalid TOML in {path}: {exc}")
    for section in ("fedora", "iso", "kickstart", "output"):
        if section not in cfg:
            raise BuildError(f"config missing [{section}] section: {path}")
    return cfg


def require_under_root(path: Path, what: str) -> Path:
    """Resolve `path` and refuse anything outside the repository root.

    podman mounts exactly ROOT at /work, so a path outside it can never
    work; the naive alternative (Path.relative_to) raises a bare ValueError,
    which main() does not catch, instead of the clean error the CLI contract
    promises everywhere else."""
    p = path.resolve()
    if p != ROOT and ROOT not in p.parents:
        raise BuildError(
            f"{what} must be inside the repository root ({ROOT}): {path}"
        )
    return p


def repo_path(value: str) -> Path:
    """Resolve a config path against the repository root, contained in it."""
    p = Path(value)
    return require_under_root(p if p.is_absolute() else ROOT / p, "config path")


# --------------------------------------------------------------------------
# pure helpers (unit-tested)
# --------------------------------------------------------------------------

def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def flatten_ks(entry: Path, root: Path | None = None) -> tuple[str, list[str]]:
    """Recursively resolve %include directives.

    Include paths are relative to the tree root (the entry file's parent).
    Returns (flattened_text, trace) where trace lists files in visit order.
    """
    root = (root or entry.parent).resolve()
    trace: list[str] = []
    body = _flatten_file(entry.resolve(), root, [], trace)
    header = [
        "# AUTO-GENERATED by kickbake.py flatten -- DO NOT EDIT.",
        f"# Generated: {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
        f"# Entry:     {entry}",
        "# Edit the files under kickstart/ instead, then re-run flatten.",
        "",
    ]
    return "\n".join(header + body) + "\n", trace


def _flatten_file(path: Path, root: Path, stack: list[Path],
                  trace: list[str]) -> list[str]:
    rel = path.relative_to(root)
    if path in stack:
        chain = " -> ".join(str(p.relative_to(root)) for p in stack + [path])
        raise BuildError(f"%include cycle detected: {chain}")
    if not path.is_file():
        raise BuildError(f"%include target not found: {rel} (expected {path})")
    trace.append(f"{'  ' * len(stack)}{rel}")
    out: list[str] = []
    stack.append(path)
    for line in path.read_text(encoding="utf-8").splitlines():
        m = INCLUDE_RE.match(line)
        if not m:
            out.append(line)
            continue
        target = m.group(1).strip().strip("'\"")
        if "://" in target:
            raise BuildError(
                f"{rel}: cannot flatten URL include '{target}' offline "
                "(legacy KICKBOOT token?). Use a path relative to the "
                "kickstart tree root."
            )
        if target.startswith("/"):
            # Runtime include (e.g. /tmp/... generated by %pre on the
            # install machine) -- pass through verbatim, never resolve.
            trace.append(f"{'  ' * len(stack)}{target} (runtime)")
            out.append(line)
            continue
        child = (root / target).resolve()
        if child != root and root not in child.parents:
            raise BuildError(
                f"{rel}: %include '{target}' escapes the kickstart tree "
                f"root ({root})"
            )
        out.append(f"# >>> begin include {target} (from {rel})")
        out.extend(_flatten_file(child, root, stack, trace))
        out.append(f"# <<< end include {target}")
    stack.pop()
    return out


def output_paths(cfg: dict, stamp: str | None = None) -> tuple[Path, Path]:
    """output/fedora-plasma-44-kickbake-26.09.07.iso (+ .ks)

    <name>-<fedora release>-<YY.MM.DD>, .iso and .ks sharing the
    same base. Year-first keeps directory listings chronological. The
    trailing date is today (local time). Same-day rebuilds never
    overwrite: when either file already exists, a -N counter
    (-1, -2, ...) is appended for the pair. `stamp` defaults to today
    (local time); callers that must agree on one date (build) pass it
    explicitly so the filename and the menu title cannot diverge.

    The Fedora release comes from the config, never from the source ISO's
    filename: the file may be renamed freely (verify-iso hashes its
    contents), and a netinst refresh within one release must not change
    the naming scheme."""
    name = cfg["output"].get("name", "fedora-plasma")
    release = cfg["fedora"]["release"]
    outdir = repo_path(cfg["output"].get("dir", "output"))
    if stamp is None:
        stamp = datetime.now().strftime("%y.%m.%d")
    base = f"{name}-{release}-kickbake-{stamp}"
    iso = outdir / f"{base}.iso"
    ks = outdir / f"{base}.ks"
    n = 1
    while iso.exists() or ks.exists():
        iso = outdir / f"{base}-{n}.iso"
        ks = outdir / f"{base}-{n}.ks"
        n += 1
    return iso, ks


def write_checksum_file(iso_path: Path) -> Path:
    digest = sha256_file(iso_path)
    ck_path = iso_path.with_suffix(iso_path.suffix + ".sha256")
    ck_path.write_text(f"{digest}  {iso_path.name}\n", encoding="utf-8")
    return ck_path


# --------------------------------------------------------------------------
# podman plumbing
# --------------------------------------------------------------------------

def require_podman() -> None:
    """Raise BuildError (not FileNotFoundError) when podman is absent.

    main() only catches BuildError, so without this the first
    subprocess.run(["podman", ...]) surfaces as a raw traceback."""
    if shutil.which("podman") is None:
        raise BuildError(
            "podman not found on PATH -- install rootless podman and re-run "
            "(see the README requirements)"
        )


def podman_run(cfg: dict, container_args: list[str],
               stream: bool = False) -> subprocess.CompletedProcess:
    """Run a command in the toolchain container with the repo at /work.

    label=disable avoids recursive SELinux relabeling of the multi-GB
    source ISO on SELinux hosts (the Fedora VM); the container is a
    trusted local build tool.

    stream=True attaches a TTY and inherits stdio so long-running steps
    (dnf downloads) show their live progress meters; the returned
    CompletedProcess carries no captured output."""
    require_podman()
    cmd = [
        "podman", "run", "--rm",
        "--volume", f"{ROOT}:/work",
        "--security-opt", "label=disable",
        "--workdir", "/work",
    ]
    if stream:
        cmd += ["--tty"]
        return subprocess.run(cmd + [cfg["fedora"]["builder_image"],
                                     *container_args])
    return subprocess.run(cmd + [cfg["fedora"]["builder_image"],
                                 *container_args],
                          capture_output=True, text=True)


def ensure_builder_image(cfg: dict, rebuild: bool = False) -> None:
    require_podman()
    image = cfg["fedora"]["builder_image"]
    exists = subprocess.run(
        ["podman", "image", "exists", image], capture_output=True
    ).returncode == 0
    if exists and not rebuild:
        return
    print(f"[image] building toolchain image {image} (first run only)...")
    proc = subprocess.run(
        ["podman", "build", "-t", image, str(ROOT / "podman")]
    )
    if proc.returncode != 0:
        raise BuildError(f"podman build failed for {image}")


def ksvalidator_version(cfg: dict) -> str:
    """Discover the F<release> syntax version from the container's
    ksvalidator itself -- never hardcode it."""
    rel = cfg["fedora"]["release"]
    proc = podman_run(cfg, ["ksvalidator", "--listversions"])
    if proc.returncode != 0:
        raise BuildError(f"ksvalidator --listversions failed:\n{proc.stderr.strip()}")
    versions = [ln.strip() for ln in proc.stdout.splitlines() if ln.strip()]
    want = f"F{rel}"
    if want not in versions:
        raise BuildError(
            f"ksvalidator has no syntax version '{want}'; available: "
            + ", ".join(versions)
        )
    return want


# --------------------------------------------------------------------------
# workflow steps
# --------------------------------------------------------------------------

def do_flatten(cfg: dict, flat: Path) -> Path:
    entry = repo_path(cfg["kickstart"]["entry"])
    if not entry.is_file():
        raise BuildError(f"kickstart entry not found: {entry}")
    text, trace = flatten_ks(entry)
    flat.parent.mkdir(parents=True, exist_ok=True)
    flat.write_text(text, encoding="utf-8")
    print("[flatten] include tree:")
    for line in trace:
        print(f"          {line}")
    print(f"[flatten] wrote {flat.relative_to(ROOT)}")
    return flat


def classify_ksvalidator(lines: list[str]) -> tuple[list[str], list[str]]:
    """Split ksvalidator output into (cosmetic, non_cosmetic) lines.

    Pure -- no I/O -- so it is unit-tested directly.

    cosmetic     : matches a KNOWN_COSMETIC_WARNINGS pattern (the
                   pykickstart btrfs-volume quirk; see that constant).
    non_cosmetic : everything else except the "Checking kickstart file"
                   progress line, i.e. the output that actually matters.

    A non-zero exit code with non-cosmetic output is a hard failure. A zero
    exit code with non-cosmetic output is a warning that must still be
    shown: dropping it silently hides a future ksvalidator complaint whose
    exit code we did not anticipate.
    """
    cosmetic = [ln for ln in lines
                if any(pat in ln for pat in KNOWN_COSMETIC_WARNINGS)]
    non_cosmetic = [ln for ln in lines
                    if ln not in cosmetic
                    and not ln.startswith("Checking kickstart file")]
    return cosmetic, non_cosmetic


def do_validate(cfg: dict, flat: Path) -> None:
    version = ksvalidator_version(cfg)
    rel = flat.relative_to(ROOT)
    print(f"[validate] ksvalidator -v {version} {rel}")
    # Runtime includes (%pre-generated) only exist on the install machine;
    # strip them before validating the rest of the file.
    script = ("sed '/^%include \\/tmp\\//d' /work/" + str(rel)
              + " > /tmp/vflat.ks && ksvalidator -v " + version
              + " /tmp/vflat.ks")
    proc = podman_run(cfg, ["bash", "-c", script])
    lines = [ln.strip() for ln in (proc.stdout + proc.stderr).splitlines()
             if ln.strip()]
    cosmetic, non_cosmetic = classify_ksvalidator(lines)
    if proc.returncode != 0 and non_cosmetic:
        raise BuildError("kickstart validation failed:\n"
                         + "\n".join(non_cosmetic))
    for ln in non_cosmetic:
        print(f"[validate] NOTE ksvalidator output (exit 0): {ln}")
    for ln in cosmetic:
        print(f"[validate] NOTE known-cosmetic warning (see kickbake.py): {ln}")
    print("[validate] OK"
          + (" (known-cosmetic warnings ignored)" if cosmetic else ""))


def verify_source_iso(cfg: dict) -> str:
    """Returns the computed digest. Raises on mismatch. Prints guidance
    when the expected hash is not pinned yet."""
    iso = repo_path(cfg["iso"]["source"])
    if not iso.is_file():
        raise BuildError(f"source ISO not found: {iso}")
    expected = str(cfg["iso"].get("expected_sha256", "")).strip().lower()
    print(f"[verify] sha256 {iso.relative_to(ROOT)} "
          f"({iso.stat().st_size / 2**30:.2f} GiB)")
    actual = sha256_file(iso)
    if not expected:
        print(f"[verify] computed: {actual}")
        raise BuildError(
            "expected_sha256 is not pinned in config/kickbake.toml. Take the "
            "official value from Fedora's CHECKSUM file for this ISO and "
            "set it, then re-run."
        )
    if actual != expected:
        raise BuildError(
            f"checksum mismatch!\n  expected: {expected}\n  actual:   {actual}"
        )
    print(f"[verify] OK ({actual})")
    return actual


def _official_checksum(value: str, iso_name: str) -> str:
    """Accepts a bare sha256 or the path of a Fedora-style CHECKSUM file
    (lines like: SHA256 (name.iso) = <hash>). Returns the lowercase hash,
    or raises BuildError."""
    path = Path(value)
    if path.is_file():
        for line in path.read_text(
                encoding="utf-8", errors="replace").splitlines():
            m = re.match(r"SHA256\s*\((.+?)\)\s*=\s*([0-9a-fA-F]{64})\s*$",
                         line.strip())
            if m and m.group(1) == iso_name:
                return m.group(2).lower()
        raise BuildError(
            f"pin-iso: no SHA256 entry for '{iso_name}' in {path}")
    value = value.strip().lower()
    if re.fullmatch(r"[0-9a-f]{64}", value):
        return value
    raise BuildError(
        "pin-iso: --checksum must be a sha256 hash or a CHECKSUM file path")


def cmd_pin_iso(cfg: dict, args: argparse.Namespace) -> int:
    """pin-iso <new-iso> --checksum <sha256|CHECKSUM-file>

    User-driven pinning of a NEW source ISO: verifies it against the
    OFFICIAL checksum, copies it into assets/, and rewrites exactly two
    lines of the config ([iso] source + expected_sha256). No network,
    no discovery. The previous ISO stays in assets/ for manual removal."""
    new_iso = Path(args.iso).resolve()
    if not new_iso.is_file():
        raise BuildError(f"pin-iso: file not found: {new_iso}")
    if new_iso.suffix.lower() != ".iso":
        raise BuildError(f"pin-iso: not an .iso file: {new_iso.name}")
    official = _official_checksum(args.checksum, new_iso.name)
    actual = sha256_file(new_iso).lower()
    if actual != official:
        raise BuildError(
            "pin-iso: checksum mismatch vs the official value -- refusing "
            f"to pin.\n  official: {official}\n  computed: {actual}")
    dest = ROOT / "assets" / new_iso.name
    if dest.resolve() != new_iso:
        shutil.copy2(new_iso, dest)
    config_path = Path(args.config).resolve()
    text = config_path.read_text(encoding="utf-8")
    # Replacement callables, never f-string replacements: re.subn interprets
    # backslash escapes in a replacement string, so a filename containing
    # \1 or \g<...> would corrupt the config (or raise) instead of being
    # written literally.
    text, n_source = re.subn(r'(?m)^source = ".*"$',
                             lambda m: f'source = "assets/{new_iso.name}"',
                             text)
    text, n_hash = re.subn(r'(?m)^expected_sha256 = ".*"$',
                           lambda m: f'expected_sha256 = "{actual}"', text)
    if n_source != 1 or n_hash != 1:
        raise BuildError(
            f"pin-iso: config update unsafe (source matches: {n_source}, "
            f"hash matches: {n_hash}) -- nothing was written.")
    config_path.write_text(text, encoding="utf-8")
    print(f"[pin-iso] pinned {new_iso.name}")
    print(f"[pin-iso]   sha256: {actual}")
    if dest.resolve() != new_iso:
        print(f"[pin-iso]   installed: {dest}")
        print(f"[pin-iso]   note: the original file remains at {new_iso} "
              "-- remove it manually if unwanted")
    print("[pin-iso] next: python3 kickbake.py verify-iso, then build")
    return 0


def read_volid(cfg: dict, iso: Path) -> str:
    """Read the ISO's volume id via xorriso in the container."""
    rel = iso.relative_to(ROOT)
    proc = podman_run(cfg, [
        "bash", "-c",
        "xorriso -indev /work/" + str(rel) + " 2>&1 | "
        "sed -n \"s/^Volume id *: '\\(.*\\)'$/\\1/p\"",
    ])
    volid = proc.stdout.strip()
    if not volid:
        raise BuildError(f"could not read volume id of {rel}")
    return volid


def do_mkksiso(cfg: dict, flat: Path, out: Path, stage: Path,
               volid: str, stamp: str) -> Path:
    """mkksiso stage: embed kickstart + offline repo, add kernel args.
    Returns the STAGE iso; ESP rebuild happens in do_compose_offline."""
    iso = repo_path(cfg["iso"]["source"])
    out.parent.mkdir(parents=True, exist_ok=True)
    for p in (out, stage):
        if p.exists():
            p.unlink()
    repo = repo_path(cfg["build"].get("repo_dir", "cache/repo"))
    if not (repo / ".done").is_file():
        raise BuildError(
            f"offline repo not ready: {repo.relative_to(ROOT)}/.done missing "
            "(build cache/repo first -- see README)"
        )
    cmd = ["mkksiso", "--ks", f"/work/{flat.relative_to(ROOT)}"]
    cmd += ["-a", f"/work/{repo.relative_to(ROOT)}"]
    cmd += ["-c", f"inst.repo=hd:LABEL={volid}:/repo"]
    # Menu title brand: KickBake <build date YY.MM.DD>, matching the dated
    # output name, e.g. "Install Fedora 44 - KickBake 26.09.14". The typed
    # confirmation and GRUB auth live in compose-offline.sh hardening, not
    # the title. `stamp` is computed once by cmd_build so the title, the
    # output filename and the output verification cannot straddle midnight.
    rel = cfg["fedora"]["release"]
    cmd += ["-R", f"Install Fedora {rel}",
            f"Install Fedora {rel} - KickBake {stamp}"]
    if cfg.get("build", {}).get("skip_mkefiboot", False):
        cmd.append("--skip-mkefiboot")
    cmd += [
        f"/work/{iso.relative_to(ROOT)}",
        f"/work/{stage.relative_to(ROOT)}",
    ]
    proc = podman_run(cfg, cmd)
    if proc.returncode != 0:
        detail = (proc.stdout + proc.stderr).strip()
        raise BuildError(f"mkksiso failed:\n{detail}")
    if not stage.is_file():
        raise BuildError(f"mkksiso reported success but {stage} is missing")
    print(f"[mkksiso] stage {stage.relative_to(ROOT)} "
          f"({stage.stat().st_size / 2**30:.2f} GiB)")
    return stage


def do_compose_offline(cfg: dict, stage: Path, out: Path,
                       volid: str) -> Path:
    """Rebuild the embedded ESP rootlessly (mkfs.vfat -C + mcopy +
    xorriso append_partition) so UEFI boots see the kickstart args."""
    if out.exists():
        out.unlink()
    grub_pw = os.environ.get("KICKBAKE_GRUB_PW", "kickbake")
    proc = podman_run(cfg, [
        "bash", "/work/podman/compose-offline.sh",
        f"/work/{stage.relative_to(ROOT)}",
        f"/work/{out.relative_to(ROOT)}",
        volid,
        grub_pw,
    ])
    if proc.returncode != 0:
        detail = (proc.stdout + proc.stderr).strip()
        raise BuildError(f"compose-offline failed:\n{detail}")
    if not out.is_file():
        raise BuildError(f"compose-offline reported success but {out} missing")
    print(f"[compose] wrote {out.relative_to(ROOT)} "
          f"({out.stat().st_size / 2**30:.2f} GiB)")
    return out


def do_build_repo(cfg: dict) -> None:
    """Build the offline KDE repository into cache/repo (Packages/ +
    repodata/ + .done marker). Downloads the @<group> closure once.

    Critical: repodata is generated WITH Fedora's comps/group metadata --
    without it Anaconda cannot resolve @^kde-desktop/@core at install time
    ("No group metadata available", "0 packages selected"). The repo is
    then self-verified by resolving the group against ONLY this repo."""
    repo = repo_path(cfg["build"].get("repo_dir", "cache/repo"))
    rel = repo.relative_to(ROOT)
    # Anaconda resolves the environment AND unconditionally adds @core
    # (LOG-FINDINGS: "No match for group package: audit/dnf5/..."), so the
    # closure and the self-verification must both cover the same spec.
    groups = cfg["build"].get("repo_groups", "kde-desktop core standard")
    extras = cfg["build"].get("repo_extra_packages", "kernel")
    release = cfg["fedora"]["release"]
    base = cfg["fedora"].get(
        "everything_base",
        "https://dl.fedoraproject.org/pub/fedora/linux/releases/"
        f"{release}/Everything/x86_64/os",
    )
    script = "\n".join([
        "set -e",
        f"if [ -e /work/{rel}/.done ]; then echo '[repo] already built'; exit 0; fi",
        f"mkdir -p /work/{rel}/Packages /work/cache/dnf-cache",
        "# 1. official Fedora comps (group + environment definitions)",
        f"curl -fsSL {base}/repodata/repomd.xml -o /tmp/repomd.xml",
        "COMPS=$(grep -o 'href=\"repodata/[^\"]*comps[^\"]*\"' /tmp/repomd.xml "
        "| head -1 | cut -d'\"' -f2)",
        "test -n \"$COMPS\"",
        f"curl -fsSL {base}/$COMPS -o /tmp/comps.comp",
        "case \"$COMPS\" in"
        " *.gz) gunzip -c /tmp/comps.comp > /tmp/comps.xml ;;"
        " *.zst) zstd -dc /tmp/comps.comp > /tmp/comps.xml ;;"
        " *.xz) xz -dc /tmp/comps.comp > /tmp/comps.xml ;;"
        " *) cp /tmp/comps.comp /tmp/comps.xml ;; esac",
        "test -s /tmp/comps.xml",
        "# 2. package closure for the requested environment",
        f"dnf -y -q --releasever={release} --use-host-config "
        "--installroot=/tmp/void --setopt=cachedir=/work/cache/dnf-cache "
        f"group install {groups} --downloadonly",
        f"dnf -y -q --releasever={release} --use-host-config "
        "--installroot=/tmp/void --setopt=cachedir=/work/cache/dnf-cache "
        f"install {extras} --downloadonly",
        f"find /work/cache/dnf-cache -name '*.rpm' -exec mv {{}} "
        f"/work/{rel}/Packages/ \\;",
        "# 2b. prune superseded versions: keep only the newest rpm per name",
        "# ${stem%-*-*} assumes NEVRA name-[epoch:]version-release, so an",
        "# epoch (name-1:1.2-3) would stay in the key and two rpms could look",
        "# like different names. Harmless today; revisit if epochs become common.",
        f"cd /work/{rel}/Packages",
        "declare -A newest=()",
        "for f in *.rpm; do",
        "    [ -e \"$f\" ] || continue",
        "    stem=\"${f%.rpm}\"; name=\"${stem%-*-*}\"",
        "    [ -n \"$name\" ] || continue",
        "    newest[$name]=$(printf '%s\\n%s\\n' \"${newest[$name]:-}\" \"$f\" "
        "| sort -V | tail -n 1)",
        "done",
        "for f in *.rpm; do",
        "    stem=\"${f%.rpm}\"; name=\"${stem%-*-*}\"",
        "    [ \"${newest[$name]:-}\" = \"$f\" ] || rm -f -- \"$f\"",
        "done",
        "cd /work",
        "# Anaconda requires the kernel package itself (F41+: not in comps)",
        f"test -n \"$(ls /work/{rel}/Packages/kernel-[0-9]*.rpm 2>/dev/null)\"",
        "# 3. metadata WITH comps",
        "dnf -q -y install createrepo_c >/dev/null 2>&1",
        f"createrepo_c --groupfile=/tmp/comps.xml /work/{rel}",
        "# 4. self-verify: resolve the group against ONLY this repo",
        # Both verify passes reuse the persistent /work cache; only the
        # installroots must exist. (/tmp/verify-cache was never referenced.)
        f"mkdir -p /tmp/verify /tmp/verify2",
        f"dnf -y -q --disablerepo='*' --repofrompath=kb,/work/{rel} "
        f"--releasever={release} --installroot=/tmp/verify "
        f"--setopt=cachedir=/work/cache/dnf-cache group install {groups} "
        "--downloadonly",
        f"dnf -y -q --disablerepo='*' --repofrompath=kb,/work/{rel} "
        f"--releasever={release} --installroot=/tmp/verify2 "
        f"--setopt=cachedir=/work/cache/dnf-cache install {extras} "
        "--downloadonly",
        # set -e makes a failed resolve fatal; step 2 moved every rpm out
        # of the cache, so these passes repopulate it from the local repo
        # (fast, no network) -- this check proves they actually resolved.
        "test -n \"$(find /work/cache/dnf-cache -name '*.rpm' | head -1)\"",
        f"touch /work/{rel}/.done",
        f"echo \"[repo] ready + comps + self-verified: "
        f"$(ls /work/{rel}/Packages | wc -l) packages\"",
    ])
    # Stream: the dnf download meters and every step boundary render live
    # (this is the longest step of the build -- silent is unacceptable).
    proc = podman_run(cfg, ["bash", "-c", script], stream=True)
    if proc.returncode != 0 or not (repo / ".done").is_file():
        raise BuildError(
            "offline repo build failed -- see the live output above")


def do_verify_output(cfg: dict, out: Path, volid: str, ks: Path,
                     stamp: str) -> None:
    """Prove the composed ISO is kickstart-enabled, self-contained and
    bootable: the tree grub.cfg (BIOS + UEFI copies) carries
    inst.ks/inst.repo; the HIDDEN ESP (appended GPT partition 2) carries
    them too; /repo/repodata and the kickstart exist in the tree; El
    Torito records survived. Both UEFI menus must be lean (no media
    test) and carry the KickBake <date> title."""
    rel = out.relative_to(ROOT)
    script = (
        "V=/work/" + str(rel) + "; "
        "xorriso -osirrox on -indev $V -extract /boot/grub2/grub.cfg "
        "/tmp/menu.cfg >/dev/null 2>&1 && "
        "grep -q 'requires UEFI' /tmp/menu.cfg && echo TREE_HALT_OK; "
        "xorriso -osirrox on -indev $V -extract /EFI/BOOT/grub.cfg "
        "/tmp/efi.cfg >/dev/null 2>&1 && "
        "grep -q 'inst.ks=' /tmp/efi.cfg && "
        "grep -q 'inst.repo=' /tmp/efi.cfg && echo EFI_ARGS_OK; "
        "L=$(xorriso -indev $V 2>&1 | "
        "grep -oE 'EFI image start and load size: [0-9]+' | "
        "grep -oE '[0-9]+$'); "
        "dd if=$V of=/tmp/esp.img bs=2048 skip=$L count=20480 status=none; "
        "mtype -i /tmp/esp.img ::/EFI/BOOT/grub.cfg > /tmp/esp.cfg 2>/dev/null; "
        "grep -q 'inst.ks=' /tmp/esp.cfg && "
        "grep -q 'inst.repo=' /tmp/esp.cfg && echo ESP_ARGS_OK; "
        "grep -q 'KickBake " + stamp + "' /tmp/esp.cfg && echo TITLE_OK; "
        "grep -q 'Test this media' /tmp/esp.cfg || echo NO_TEST_ENTRY; "
        "grep -q 'superusers=\"kickbake\"' /tmp/esp.cfg && "
        "grep -q 'password_pbkdf2' /tmp/esp.cfg && echo GRUB_AUTH_OK; "
        "grep -q 'KickBake " + stamp + "' /tmp/efi.cfg && echo EFI_TITLE_OK; "
        "grep -q 'Test this media' /tmp/efi.cfg || echo EFI_NO_TEST_ENTRY; "
        "xorriso -indev $V -find /repo/repodata/repomd.xml 2>/dev/null "
        "| grep -q repomd && echo REPO_OK; "
        "xorriso -indev $V -find /repo/repodata -name '*comps*' 2>/dev/null "
        "| grep -q comps && echo COMPS_OK; "
        "xorriso -indev $V -find /" + ks.name + " 2>/dev/null "
        "| grep -q " + ks.name + " && echo KS_OK; "
        "xorriso -indev $V 2>&1 | grep -q 'El Torito' && echo ELTORITO_OK"
    )
    proc = podman_run(cfg, ["bash", "-c", script])
    text = proc.stdout + proc.stderr
    checks = {
        "BIOS tree carries the UEFI-required halt entry": "TREE_HALT_OK" in text,
        "tree UEFI grub.cfg carries inst.ks + inst.repo": "EFI_ARGS_OK" in text,
        "hidden ESP grub.cfg carries inst.ks + inst.repo": "ESP_ARGS_OK" in text,
        "/repo/repodata/repomd.xml present": "REPO_OK" in text,
        "comps group metadata in /repo/repodata": "COMPS_OK" in text,
        "kickstart file present in tree": "KS_OK" in text,
        "El Torito boot records present": "ELTORITO_OK" in text,
        f"ESP menu title carries KickBake {stamp}": "TITLE_OK" in text,
        "no 'Test this media' entry in ESP menu": "NO_TEST_ENTRY" in text,
        "GRUB auth: superusers + pbkdf2 pin the installer entry": "GRUB_AUTH_OK" in text,
        f"tree UEFI menu title carries KickBake {stamp}": "EFI_TITLE_OK" in text,
        "no 'Test this media' entry in tree UEFI menu": "EFI_NO_TEST_ENTRY" in text,
    }
    failed = [name for name, ok in checks.items() if not ok]
    if failed:
        raise BuildError(
            "output ISO verification failed: " + "; ".join(failed)
            + f"\ncontainer output:\n{text.strip()}"
        )
    print("[verify-out] tree+ESP kernel args, /repo repodata+comps, ks file, "
          "El Torito records: OK")


# --------------------------------------------------------------------------
# commands
# --------------------------------------------------------------------------

def cmd_doctor(cfg: dict | None, args: argparse.Namespace) -> int:
    """Report the environment, loading our own config.

    `main` deliberately does not pre-load the config for doctor: a broken
    config must surface as a doctor finding, not abort before the report has
    begun. The incoming `cfg` is therefore ignored (normally None)."""
    ok = True

    def check(label: str, passed: bool, detail: str = "") -> None:
        nonlocal ok
        state = "OK  " if passed else "FAIL"
        print(f"[doctor] {state} {label}" + (f" -- {detail}" if detail else ""))
        ok = ok and passed

    check("python >= 3.11 (tomllib)", tomllib is not None,
          sys.version.split()[0])
    check("podman on PATH", shutil.which("podman") is not None)
    try:
        cfg_path = require_under_root(Path(args.config), "--config")
        cfg = load_config(cfg_path)
        check("config loads", True, str(cfg_path.relative_to(ROOT)))
    except BuildError as exc:
        check("config loads", False, str(exc))
        return 1

    if shutil.which("podman") is None:
        return 1
    try:
        ensure_builder_image(cfg, rebuild=args.rebuild)
        check("toolchain image", True, cfg["fedora"]["builder_image"])
    except BuildError as exc:
        check("toolchain image", False, str(exc))
        return 1

    proc = podman_run(cfg, [
        "bash", "-c",
        "rpm -q lorax pykickstart xorriso isomd5sum && command -v mkksiso ksvalidator",
    ])
    if proc.returncode != 0:
        check("container toolchain", False, (proc.stdout + proc.stderr).strip())
        return 1
    for line in proc.stdout.splitlines():
        if line.startswith("/usr/bin"):
            continue
        print(f"[doctor]      {line}")
    check("container toolchain", True)

    try:
        version = ksvalidator_version(cfg)
        check("ksvalidator syntax version", True, version)
    except BuildError as exc:
        check("ksvalidator syntax version", False, str(exc))
        ok = False

    iso = repo_path(cfg["iso"]["source"])
    check("source ISO present", iso.is_file(),
          str(iso.relative_to(ROOT)) if iso.is_file() else f"missing: {iso}")
    pinned = bool(str(cfg["iso"].get("expected_sha256", "")).strip())
    check("expected_sha256 pinned", pinned,
          "" if pinned else "run `python3 kickbake.py verify-iso` guidance")

    print("[doctor] " + ("all good" if ok else "problems found"))
    return 0 if ok else 1


def cmd_verify_iso(cfg: dict, args: argparse.Namespace) -> int:
    try:
        verify_source_iso(cfg)
        return 0
    except BuildError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


def cmd_flatten(cfg: dict, args: argparse.Namespace) -> int:
    _, flat = output_paths(cfg)
    do_flatten(cfg, flat)
    return 0


def cmd_validate(cfg: dict, args: argparse.Namespace) -> int:
    _, flat = output_paths(cfg)
    if not flat.is_file():
        print("[validate] flat kickstart missing; flattening first")
        flat = do_flatten(cfg, flat)
    try:
        do_validate(cfg, flat)
        return 0
    except BuildError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


def cmd_repo(cfg: dict, args: argparse.Namespace) -> int:
    ensure_builder_image(cfg)
    do_build_repo(cfg)
    return 0


def cmd_build(cfg: dict, args: argparse.Namespace) -> int:
    t0 = time.monotonic()
    ensure_builder_image(cfg)
    verify_source_iso(cfg)
    # One date for the whole build: the output filename, the menu title and
    # the output verification all read this value. Recomputing it in each
    # step made a build that crossed midnight fail verification on a good ISO.
    stamp = datetime.now().strftime("%y.%m.%d")
    out, flat = output_paths(cfg, stamp)
    flat = do_flatten(cfg, flat)
    do_validate(cfg, flat)
    iso = repo_path(cfg["iso"]["source"])
    volid = read_volid(cfg, iso)
    print(f"[compose] source volume id: {volid}")
    stage = out.with_name(out.stem + ".stage.iso")
    try:
        stage = do_mkksiso(cfg, flat, out, stage, volid, stamp)
        out = do_compose_offline(cfg, stage, out, volid)
        do_verify_output(cfg, out, volid, flat, stamp)
    finally:
        # Reclaim the multi-GB intermediate on success AND on failure: a
        # failed build used to leave *.stage.iso behind in output/.
        if stage.exists():
            stage.unlink()
    ck = write_checksum_file(out)
    print(f"[sha256]  wrote {ck.relative_to(ROOT)}")
    print(f"[build]   done in {time.monotonic() - t0:.1f}s -> "
          f"{out.relative_to(ROOT)}")
    return 0


# --------------------------------------------------------------------------

DISPATCH = {
    "doctor": cmd_doctor,
    "verify-iso": cmd_verify_iso,
    "pin-iso": cmd_pin_iso,
    "flatten": cmd_flatten,
    "validate": cmd_validate,
    "repo": cmd_repo,
    "build": cmd_build,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="kickbake.py",
        description="Bake a Kickstart into a Fedora Plasma ISO (via Podman).",
    )
    parser.add_argument("--version", action="version",
                        version=f"KickBake {__version__}")
    parser.add_argument("--config", default=str(DEFAULT_CONFIG),
                        help="path to kickbake.toml (default: config/kickbake.toml)")
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("doctor", help="check environment and toolchain")
    p.add_argument("--rebuild", action="store_true",
                   help="force-rebuild the toolchain container image")

    sub.add_parser("repo", help="build the offline KDE repo into cache/repo")
    sub.add_parser("verify-iso", help="sha256 the source ISO vs pinned hash")
    p = sub.add_parser("pin-iso",
                       help="verify a NEW ISO against the official checksum "
                            "and pin it (config updated)")
    p.add_argument("iso", help="path to the new source ISO")
    p.add_argument("--checksum", required=True,
                   help="official sha256, or a Fedora-style CHECKSUM file")
    sub.add_parser("flatten", help="resolve the %%include tree to one file")
    sub.add_parser("validate", help="run ksvalidator in the container")
    sub.add_parser("build", help="full workflow: verify->flatten->validate->mkksiso")

    args = parser.parse_args(argv)
    try:
        if args.command == "doctor":
            # doctor loads its own config and reports a broken one; a
            # pre-load here would abort before that report could start.
            return DISPATCH[args.command](None, args)
        # Container-visible paths live under ROOT (podman mounts it at
        # /work), so the config must too. Resolve and check here so every
        # command reports it the same clean way.
        cfg_path = require_under_root(Path(args.config), "--config")
        args.config = str(cfg_path)
        cfg = load_config(cfg_path)
        return DISPATCH[args.command](cfg, args)
    except BuildError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
