"""Unit tests for kickbake.py — stdlib unittest only, no podman needed."""

import hashlib
import sys
import tempfile
import unittest
from datetime import datetime
from pathlib import Path
from unittest import mock

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import kickbake  # noqa: E402


class TestFlatten(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.root = Path(self._tmp.name)
        self.addCleanup(self._tmp.cleanup)

    def write(self, rel: str, text: str) -> Path:
        p = self.root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8")
        return p

    def test_nested_includes_flatten_in_order(self):
        self.write("entry.ks", "base\n%include mid/storage.ks\n%include tail.ks\n")
        self.write("mid/storage.ks", "STORAGE\n%include layout/leaf.ks\n")
        self.write("layout/leaf.ks", "LEAF\n")
        self.write("tail.ks", "TAIL\n")

        text, trace = kickbake.flatten_ks(self.root / "entry.ks", self.root)

        for needle in ("base", "STORAGE", "LEAF", "TAIL"):
            self.assertIn(needle, text)
        # leaf must appear between its including file's content and marker end
        self.assertLess(text.index("STORAGE"), text.index("LEAF"))
        self.assertLess(text.index("LEAF"), text.index("TAIL"))
        # no %include may survive flattening
        self.assertNotIn("%include", text)
        # trace lists every file exactly once, indented by nesting depth
        self.assertEqual(
            trace,
            ["entry.ks", "  mid/storage.ks", "    layout/leaf.ks", "  tail.ks"],
        )

    def test_missing_include_raises(self):
        self.write("entry.ks", "%include nonexistent.ks\n")
        with self.assertRaises(kickbake.BuildError) as ctx:
            kickbake.flatten_ks(self.root / "entry.ks", self.root)
        self.assertIn("nonexistent.ks", str(ctx.exception))

    def test_cycle_raises(self):
        self.write("a.ks", "%include b.ks\n")
        self.write("b.ks", "%include a.ks\n")
        with self.assertRaises(kickbake.BuildError) as ctx:
            kickbake.flatten_ks(self.root / "a.ks", self.root)
        self.assertIn("cycle", str(ctx.exception))

    def test_include_escaping_tree_raises(self):
        # a %include that climbs out of the tree root must fail with a
        # clean BuildError -- not a raw ValueError from Path.relative_to
        self.write("entry.ks", "%include ../outside.ks\n")
        with self.assertRaises(kickbake.BuildError) as ctx:
            kickbake.flatten_ks(self.root / "entry.ks", self.root)
        self.assertIn("escapes the kickstart tree", str(ctx.exception))

    def test_url_include_rejected(self):
        # legacy KICKBOOT token form must fail loudly, not silently pass
        self.write("entry.ks", "%include http://KICKBOOT/storage/vm-single.ks\n")
        with self.assertRaises(kickbake.BuildError) as ctx:
            kickbake.flatten_ks(self.root / "entry.ks", self.root)
        self.assertIn("KICKBOOT", str(ctx.exception))

    def test_runtime_include_passthrough(self):
        # /tmp/... includes are generated by %pre on the install machine
        # and must survive flattening verbatim, never be resolved.
        self.write("entry.ks", "rootpw --lock\n%include /tmp/kickbake-storage.ks\n")
        text, trace = kickbake.flatten_ks(self.root / "entry.ks", self.root)
        self.assertIn("%include /tmp/kickbake-storage.ks", text)
        self.assertTrue(any("runtime" in t for t in trace))

    def test_generated_header_present(self):
        self.write("entry.ks", "rootpw --lock\n")
        text, _ = kickbake.flatten_ks(self.root / "entry.ks", self.root)
        self.assertTrue(text.startswith("# AUTO-GENERATED by kickbake.py"))
        self.assertIn("rootpw --lock", text)


class TestChecksum(unittest.TestCase):
    def test_sha256_file_matches_hashlib(self):
        with tempfile.TemporaryDirectory() as tmp:
            p = Path(tmp) / "blob.bin"
            data = b"kickbake" * 1000
            p.write_bytes(data)
            self.assertEqual(kickbake.sha256_file(p),
                             hashlib.sha256(data).hexdigest())

    def test_checksum_file_format(self):
        with tempfile.TemporaryDirectory() as tmp:
            iso = Path(tmp) / "out.iso"
            iso.write_bytes(b"iso-bytes")
            ck = kickbake.write_checksum_file(iso)
            self.assertEqual(ck.name, "out.iso.sha256")
            content = ck.read_text(encoding="utf-8").rstrip("\n")
            digest, name = content.split("  ", 1)
            self.assertEqual(digest, hashlib.sha256(b"iso-bytes").hexdigest())
            self.assertEqual(name, "out.iso")


class TestOutputNaming(unittest.TestCase):
    def setUp(self):
        # The output directory must live under the repository root:
        # repo_path() enforces it, because the container only ever sees
        # ROOT (mounted at /work), so an outside dir could never work.
        tmp = tempfile.TemporaryDirectory(dir=kickbake.ROOT)
        self.addCleanup(tmp.cleanup)
        self.tmp = tmp.name

    def test_date_naming_and_same_day_counter(self):
        cfg = {
            # the source ISO's filename no longer influences the output
            # name: the Fedora release comes from [fedora] release
            "iso": {"source": "renamed-anything.iso"},
            "fedora": {"release": 44},
            "output": {"dir": self.tmp, "name": "fedora-plasma"},
        }
        iso, ks = kickbake.output_paths(cfg)
        base = "fedora-plasma-44-kickbake-" + datetime.now().strftime(
            "%y.%m.%d")
        self.assertEqual(iso.name, f"{base}.iso")
        self.assertEqual(ks.name, f"{base}.ks")
        # a same-day rebuild never overwrites: the pair gains a -N counter
        (Path(self.tmp) / f"{base}.iso").write_bytes(b"x")
        (Path(self.tmp) / f"{base}.ks").write_text("x", encoding="utf-8")
        iso2, ks2 = kickbake.output_paths(cfg)
        self.assertEqual(iso2.name, f"{base}-1.iso")
        self.assertEqual(ks2.name, f"{base}-1.ks")


class TestValidateClassification(unittest.TestCase):
    """do_validate must never swallow ksvalidator output."""

    def test_progress_line_is_dropped(self):
        cosmetic, non_cosmetic = kickbake.classify_ksvalidator(
            ["Checking kickstart file /tmp/vflat.ks"])
        self.assertEqual(cosmetic, [])
        self.assertEqual(non_cosmetic, [])

    def test_known_cosmetic_is_separated(self):
        pat = kickbake.KNOWN_COSMETIC_WARNINGS[0]
        cosmetic, non_cosmetic = kickbake.classify_ksvalidator(
            ["Checking kickstart file /tmp/vflat.ks",
             pat,
             "Some future ksvalidator warning"])
        self.assertEqual(cosmetic, [pat])
        self.assertEqual(non_cosmetic, ["Some future ksvalidator warning"])


class TestPathContainment(unittest.TestCase):
    """F-3: everything the container sees lives under ROOT (/work)."""

    def test_relative_path_resolves_under_root(self):
        p = kickbake.repo_path("assets/anything.iso")
        self.assertEqual(p.parent, kickbake.ROOT / "assets")

    def test_absolute_path_inside_root_is_accepted(self):
        target = kickbake.ROOT / "output"
        self.assertEqual(kickbake.repo_path(str(target)), target)

    def test_escapes_are_rejected(self):
        for bad in ("/etc/passwd", "../../etc/passwd",
                    "a/../../../etc/passwd"):
            with self.assertRaises(kickbake.BuildError):
                kickbake.repo_path(bad)

    def test_root_itself_is_contained(self):
        self.assertEqual(
            kickbake.require_under_root(kickbake.ROOT, "thing"),
            kickbake.ROOT)


class TestRequirePodman(unittest.TestCase):
    """F-3: a missing podman must be a BuildError, not FileNotFoundError."""

    def test_missing_podman_raises_build_error(self):
        with mock.patch("kickbake.shutil.which", return_value=None):
            with self.assertRaises(kickbake.BuildError):
                kickbake.require_podman()

    def test_present_podman_is_silent(self):
        with mock.patch("kickbake.shutil.which",
                        return_value="/usr/bin/podman"):
            self.assertIsNone(kickbake.require_podman())


if __name__ == "__main__":
    unittest.main()
