"""Unit tests for kickbake.py — stdlib unittest only, no podman needed."""

import hashlib
import sys
from datetime import datetime
import tempfile
import unittest
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import kickbake  # noqa: E402


class TestFlatten(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.root = Path(self._tmp.name)
        self.addCleanup(self._tmp.cleanup)

    def write(self, rel: str, text: str) -> Path:
        p = self.root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8")
        return p

    def test_nested_includes_flatten_in_order(self):
        self.write("entry.ks", "base\n%include mid/storage.ks\n%include tail.ks\n")
        self.write("mid/storage.ks", "STORAGE\n%include layout/leaf.ks\n")
        self.write("layout/leaf.ks", "LEAF\n")
        self.write("tail.ks", "TAIL\n")

        text, trace = kickbake.flatten_ks(self.root / "entry.ks", self.root)

        for needle in ("base", "STORAGE", "LEAF", "TAIL"):
            self.assertIn(needle, text)
        # leaf must appear between its including file's content and marker end
        self.assertLess(text.index("STORAGE"), text.index("LEAF"))
        self.assertLess(text.index("LEAF"), text.index("TAIL"))
        # no %include may survive flattening
        self.assertNotIn("%include", text)
        # trace lists every file exactly once, indented by nesting depth
        self.assertEqual(
            trace,
            ["entry.ks", "  mid/storage.ks", "    layout/leaf.ks", "  tail.ks"],
        )

    def test_missing_include_raises(self):
        self.write("entry.ks", "%include nonexistent.ks\n")
        with self.assertRaises(kickbake.BuildError) as ctx:
            kickbake.flatten_ks(self.root / "entry.ks", self.root)
        self.assertIn("nonexistent.ks", str(ctx.exception))

    def test_cycle_raises(self):
        self.write("a.ks", "%include b.ks\n")
        self.write("b.ks", "%include a.ks\n")
        with self.assertRaises(kickbake.BuildError) as ctx:
            kickbake.flatten_ks(self.root / "a.ks", self.root)
        self.assertIn("cycle", str(ctx.exception))

    def test_url_include_rejected(self):
        # legacy KICKBOOT token form must fail loudly, not silently pass
        self.write("entry.ks", "%include http://KICKBOOT/storage/vm-single.ks\n")
        with self.assertRaises(kickbake.BuildError) as ctx:
            kickbake.flatten_ks(self.root / "entry.ks", self.root)
        self.assertIn("KICKBOOT", str(ctx.exception))

    def test_runtime_include_passthrough(self):
        # /tmp/... includes are generated by %pre on the install machine
        # and must survive flattening verbatim, never be resolved.
        self.write("entry.ks", "rootpw --lock\n%include /tmp/kickbake-storage.ks\n")
        text, trace = kickbake.flatten_ks(self.root / "entry.ks", self.root)
        self.assertIn("%include /tmp/kickbake-storage.ks", text)
        self.assertTrue(any("runtime" in t for t in trace))

    def test_generated_header_present(self):
        self.write("entry.ks", "rootpw --lock\n")
        text, _ = kickbake.flatten_ks(self.root / "entry.ks", self.root)
        self.assertTrue(text.startswith("# AUTO-GENERATED by kickbake.py"))
        self.assertIn("rootpw --lock", text)


class TestChecksum(unittest.TestCase):
    def test_sha256_file_matches_hashlib(self):
        with tempfile.TemporaryDirectory() as tmp:
            p = Path(tmp) / "blob.bin"
            data = b"kickbake" * 1000
            p.write_bytes(data)
            self.assertEqual(kickbake.sha256_file(p),
                             hashlib.sha256(data).hexdigest())

    def test_checksum_file_format(self):
        with tempfile.TemporaryDirectory() as tmp:
            iso = Path(tmp) / "out.iso"
            iso.write_bytes(b"iso-bytes")
            ck = kickbake.write_checksum_file(iso)
            self.assertEqual(ck.name, "out.iso.sha256")
            content = ck.read_text(encoding="utf-8").rstrip("\n")
            digest, name = content.split("  ", 1)
            self.assertEqual(digest, hashlib.sha256(b"iso-bytes").hexdigest())
            self.assertEqual(name, "out.iso")


class TestOutputNaming(unittest.TestCase):
    def setUp(self):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.tmp = tmp.name

    def test_date_naming_and_same_day_counter(self):
        cfg = {
            "iso": {
                "source": "assets/Fedora-Everything-netinst-x86_64-44-1.7.iso"
            },
            "output": {"dir": self.tmp, "name": "kickbake-fedora-plasma"},
        }
        iso, ks = kickbake.output_paths(cfg)
        base = "kickbake-fedora-plasma-44.1.7-" + datetime.now().strftime(
            "%y.%m.%d")
        self.assertEqual(iso.name, f"{base}.iso")
        self.assertEqual(ks.name, f"{base}.ks")
        # a same-day rebuild never overwrites: the pair gains a -N counter
        (Path(self.tmp) / f"{base}.iso").write_bytes(b"x")
        (Path(self.tmp) / f"{base}.ks").write_text("x", encoding="utf-8")
        iso2, ks2 = kickbake.output_paths(cfg)
        self.assertEqual(iso2.name, f"{base}-1.iso")
        self.assertEqual(ks2.name, f"{base}-1.ks")


if __name__ == "__main__":
    unittest.main()
